version: 2.1

orbs:
  node: circleci/node@5.0.1
  heroku: circleci/heroku@2.0.0
  docker: circleci/docker@2.1.4

jobs:
  build: #name of the job
    docker: #powered by docker
      - image: cimg/node:16.10 #pulling down image of node 16.10
    steps: #steps of this job (a list defined by '-')
      - checkout #pull down source code from github
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: georgiealx/education-space
          tag: v1.0.1
      - docker/push:
          image: georgiealx/education-space
          tag: v1.0.1
  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - checkout
      - heroku/install
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku container:push web -a devopsproj
            heroku container:release web -a devopsproj

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
      - deploy:
          requires:
            - publish
