version: 2.1

orbs:
  node: circleci/node@5.0.1
  heroku: circleci/heroku@2.0.0
  docker: circleci/docker@2.1.4
  snyk: snyk/snyk@1.5.0

jobs:
  build: #name of the job
    docker: #powered by docker
      - image: cimg/node:16.10 #pulling down image of node 16.10
    steps: #steps of this job (a list defined by '-')
      - checkout #pull down source code from github
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  scan:
    docker:
      - image: cimg/node:16.10
    environment:
      IMAGE_NAME: georgiealx/education-space
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run: docker build -t $IMAGE_NAME .
      - snyk/scan:
          docker-image-name: $IMAGE_NAME
  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: georgiealx/education-space
          tag: v1.0.1
      - docker/push:
          image: georgiealx/education-space
          tag: v1.0.1
  # deploy:
  #   docker:
  #     - image: cimg/node:16.10
  #   steps:
  #     - setup_remote_docker
  #     - checkout
  #     - heroku/install
  #     - run:
  #         name: Heroku Container Push
  #         command: |
  #           heroku container:login
  #           heroku container:push web -a devopsproj
  #           heroku container:release web -a devopsproj
  pull-and-deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - heroku/install
      - docker/pull:
          images: georgiealx/education-space:v1.0.1
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            docker tag georgiealx/education-space:v1.0.1 registry.heroku.com/devopsproj/web
            # format docker tag <image name from docker hub> registry.heroku.com/<app-name>/web
            docker push registry.heroku.com/devopsproj/web
            # format --- docker push registry.heroku.com/<app-name>/web
            heroku container:release web -a devopsproj

workflows:
  simple_workflow:
    jobs:
      - build
        # filter:
      - test:
          requires:
            - build
      - scan:
          requires:
            - test
      - publish:
          requires:
            - test
      # - deploy:
      #     requires:
      #       - publish
      - pull-and-deploy:
          requires:
            - publish
# workflows:
#   build-deploy:
#     jobs:
#       - js_build
#       - build_server_pdf # job to conditionally run based on filter on branch name
#           filters:
#             branches:
#               only: /server\/.*/
